# Generated by Django 5.2.7 on 2025-12-02 17:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0004_alter_message_options_remove_message_recipient_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_removed',
            field=models.BooleanField(default=False, help_text='Whether this message has been removed by a moderator'),
        ),
        migrations.AddField(
            model_name='message',
            name='removal_reason',
            field=models.TextField(blank=True, help_text='Reason for removal'),
        ),
        migrations.AddField(
            model_name='message',
            name='removed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='removed_by',
            field=models.ForeignKey(blank=True, help_text='Moderator who removed this message', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages_removed', to=settings.AUTH_USER_MODEL),
        ),
    ]
