# Generated by Django 5.2.7 on 2025-11-13 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_info', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='display_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
