# Generated by Django 5.2.7 on 2025-12-02 17:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_dashboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_removed',
            field=models.BooleanField(default=False, help_text='Whether this post has been removed by a moderator'),
        ),
        migrations.AddField(
            model_name='post',
            name='removal_reason',
            field=models.TextField(blank=True, help_text='Reason for removal'),
        ),
        migrations.AddField(
            model_name='post',
            name='removed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='removed_by',
            field=models.ForeignKey(blank=True, help_text='Moderator who removed this post', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts_removed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('moderator', 'Moderator'), ('admin', 'Admin')], default='user', max_length=10),
        ),
        migrations.CreateModel(
            name='Flag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('post', 'Post'), ('message', 'Message'), ('profile', 'Profile')], help_text='Type of content being reported', max_length=20)),
                ('content_id', models.IntegerField(help_text='ID of the flagged item')),
                ('reason', models.CharField(choices=[('spam', 'Spam or Advertising'), ('harassment', 'Harassment or Bullying'), ('inappropriate', 'Inappropriate Content'), ('misinformation', 'Misinformation'), ('other', 'Other')], default='other', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Additional details about why this was flagged')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('reviewed', 'Reviewed'), ('dismissed', 'Dismissed - No Action'), ('actioned', 'Action Taken')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('moderator_notes', models.TextField(blank=True, help_text='Internal notes from the moderator')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reporter', models.ForeignKey(help_text='User who reported this content', on_delete=django.db.models.deletion.CASCADE, related_name='flags_reported', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='Moderator who reviewed this flag', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flags_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='user_dashbo_status_e680cb_idx'), models.Index(fields=['content_type', 'content_id'], name='user_dashbo_content_345b22_idx')],
            },
        ),
    ]
