# Generated by Django 5.2.7 on 2025-11-15 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_dashboard', '0002_post'),
        ('user_dashboard', '0002_profile_profile_picture'),
    ]

    operations = [
    ]
