# Generated by Django 5.2.7 on 2025-10-30 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_dashboard', '0002_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default='Sustainability Post', max_length=200),
        ),
    ]
