# Generated by Django 5.2.7 on 2025-11-15 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_dashboard', '0003_merge_0002_post_0002_profile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default='Sustainability Post', max_length=200),
        ),
    ]
