# Generated by Django 5.2.7 on 2025-12-03 04:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_dashboard', '0003_profile_is_suspended_profile_reinstated_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='comments_count',
            field=models.IntegerField(default=0, help_text='Reserved for future Comment feature'),
        ),
        migrations.AddField(
            model_name='post',
            name='hashtags',
            field=models.TextField(blank=True, help_text='Comma-separated hashtags (e.g., zerowaste, climateaction)'),
        ),
        migrations.AddField(
            model_name='post',
            name='is_draft',
            field=models.BooleanField(default=False, help_text='Draft posts are not shown in feed'),
        ),
        migrations.AddField(
            model_name='post',
            name='privacy',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Friends Only')], default='public', help_text='Who can see this post', max_length=10),
        ),
        migrations.AddField(
            model_name='post',
            name='topic',
            field=models.CharField(choices=[('recycling', '♻️ Recycling & Waste'), ('living', '🌱 Sustainable Living'), ('campus', '🍃 Campus Sustainability'), ('food', '🥗 Food & Dining'), ('transport', '🚴 Transportation'), ('education', '💡 Tips & Education'), ('achievements', '🏆 Achievements'), ('discussion', '💬 General Discussion')], default='discussion', help_text='Sustainability topic category', max_length=20),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['privacy', 'is_draft', '-created_at'], name='user_dashbo_privacy_c5ccdc_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['topic', '-created_at'], name='user_dashbo_topic_4cf653_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['user', 'is_draft'], name='user_dashbo_user_id_73acd1_idx'),
        ),
        migrations.AddField(
            model_name='friendrequest',
            name='from_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_requests_sent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='friendrequest',
            name='to_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_requests_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='friendship',
            name='user1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendships_as_user1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='friendship',
            name='user2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendships_as_user2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='friendrequest',
            index=models.Index(fields=['to_user', 'status'], name='user_dashbo_to_user_f1b1e6_idx'),
        ),
        migrations.AddIndex(
            model_name='friendrequest',
            index=models.Index(fields=['from_user', 'status'], name='user_dashbo_from_us_a1ea31_idx'),
        ),
        migrations.AddConstraint(
            model_name='friendrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('from_user', 'to_user'), name='unique_pending_request'),
        ),
        migrations.AddIndex(
            model_name='friendship',
            index=models.Index(fields=['user1', 'user2'], name='user_dashbo_user1_i_f9cf54_idx'),
        ),
        migrations.AddConstraint(
            model_name='friendship',
            constraint=models.UniqueConstraint(fields=('user1', 'user2'), name='unique_friendship'),
        ),
        migrations.AddConstraint(
            model_name='friendship',
            constraint=models.CheckConstraint(condition=models.Q(('user1__lt', models.F('user2'))), name='user1_less_than_user2'),
        ),
    ]
