# Generated by Django 5.2.7 on 2025-10-30 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_dashboard', '0003_post_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
    ]
