# Generated by Django 5.2.7 on 2025-12-06 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_dashboard', '0004_friendrequest_friendship_post_comments_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='first_time_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='preferred_topics',
            field=models.TextField(blank=True, default=''),
        ),
    ]
