# Generated by Django 5.2.7 on 2025-12-09 07:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_dashboard', '0005_profile_first_time_complete_profile_preferred_topics'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(blank=True, help_text='Users who liked this post', related_name='liked_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
