# Generated by Django 5.2.7 on 2025-12-10 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_dashboard', '0007_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('friend_request', 'Friend Request'), ('friend_accept', 'Friend Request Accepted'), ('friend_removed', 'Friend Removed'), ('post_like', 'Post Liked'), ('new_message', 'New Message'), ('post_removed', 'Post Removed'), ('message_removed', 'Message Removed'), ('account_suspended', 'Account Suspended'), ('account_reinstated', 'Account Reinstated')], max_length=20),
        ),
    ]
